export const Music = [
    { id: 1, url: '/assets/audio/ambient/billsHouse.mp3', name: 'Bill' },
    { id: 2, url: '/assets/audio/ambient/casino.mp3', name: 'Casino' },
    { id: 3, url: '/assets/audio/ambient/celadeon.mp3', name: 'Celadeon' },
    { id: 4, url: '/assets/audio/ambient/cerulean.mp3', name: 'Cerulean' },
    { id: 5, url: '/assets/audio/ambient/cerulean2.mp3', name: 'Cerulean 2' },
    { id: 6, url: '/assets/audio/ambient/cinnabar.mp3', name: 'Cinnabar' },
    { id: 7, url: '/assets/audio/ambient/cycling.mp3', name: 'Cycling' },
    { id: 8, url: '/assets/audio/ambient/ending.mp3', name: 'Ending' },
    { id: 9, url: '/assets/audio/ambient/lavender.mp3', name: 'Lavender' },
    { id: 10, url: '/assets/audio/ambient/oak.mp3', name: 'Oak' },
    { id: 11, url: '/assets/audio/ambient/oaksLab.mp3', name: 'Oaks Lab' },
    { id: 12, url: '/assets/audio/ambient/palleteTown.mp3', name: 'Pallete Town' },
    { id: 13, url: '/assets/audio/ambient/pewter.mp3', name: 'Pewter' },
    { id: 14, url: '/assets/audio/ambient/pokemonCenter.mp3', name: 'Pokemon center' },
    { id: 15, url: '/assets/audio/ambient/sea.mp3', name: 'Sea' },
    { id: 16, url: '/assets/audio/ambient/stAnne.mp3', name: 'St. Anne' },
    { id: 17, url: '/assets/audio/ambient/veridian.mp3', name: 'Veridian Forest' },
    { id: 18, url: '/assets/audio/ambient/vermillion.mp3', name: 'Vermillion' },
];
