export const Themes = [
    { id: 1, img: '/assets/images/backgrounds/charizard.jpeg', name: 'Charizard' },
    { id: 2, img: '/assets/images/backgrounds/celebi.jpeg', name: 'Celebi' },
    { id: 3, img: '/assets/images/backgrounds/pikachu.jpeg', name: 'Pikachu' },
    { id: 4, img: '/assets/images/backgrounds/shinyCharizard.jpeg', name: 'Shiny Charizard' },
    { id: 5, img: '/assets/images/backgrounds/tyranitar.jpeg', name: 'Tyranitar' },
    { id: 6, img: '/assets/images/backgrounds/galarianMoltres.jpeg', name: 'Galarian Moltres' },
    { id: 7, img: '/assets/images/backgrounds/galarianZapdos.jpeg', name: 'Galarian Zapdos' },
    { id: 8, img: '/assets/images/backgrounds/galarianArticuno.jpeg', name: 'Galarian Articuno' },
    { id: 9, img: '/assets/images/backgrounds/sylveon.jpeg', name: 'Sylveon' },
    { id: 10, img: '/assets/images/backgrounds/whitePikachu.jpeg', name: 'White Pikachu' },
    { id: 11, img: '/assets/images/backgrounds/redPikachu.jpeg', name: 'Red Pikachu' },
    { id: 12, img: '/assets/images/backgrounds/greenPikachu.jpeg', name: 'Green Pikachu' },
    { id: 13, img: '/assets/images/backgrounds/bluePikachu.jpeg', name: 'Blue Pikachu' },
    { id: 14, img: '/assets/images/backgrounds/mew.jpeg', name: 'Mew' },
    { id: 15, img: '/assets/images/backgrounds/arceus.jpeg', name: 'Arceus' },
    { id: 16, img: '/assets/images/backgrounds/umbreon.jpeg', name: 'Umbreon' },
    { id: 17, img: '/assets/images/backgrounds/rayquaza.jpeg', name: 'Rayquaza' },
    { id: 18, img: '/assets/images/backgrounds/party.jpeg', name: 'Party' },
    { id: 19, img: '/assets/images/backgrounds/zarude.jpeg', name: 'Zarude' },
    { id: 20, img: '/assets/images/backgrounds/lapras.jpeg', name: 'Lapras' },
];
