export const Types = {
    bug: `../src/assets/images/types/bug.png`,
    dark: `../src/assets/images/types/dark.png`,
    dragon: '../src/assets/images/types/dragon.png',
    electric: '../src/assets/images/types/electric.png',
    fairy: '../src/assets/images/types/fairy.png',
    fighting: '../src/assets/images/types/fighting.png',
    fire: '../src/assets/images/types/fire.png',
    flying: '../src/assets/images/types/flying.png',
    ghost: '../src/assets/images/types/ghost.png',
    grass: '../src/assets/images/types/grass.png',
    ground: '../src/assets/images/types/ground.png',
    ice: '../src/assets/images/types/ice.png',
    normal: '../src/assets/images/types/normal.png',
    poison: '../src/assets/images/types/poison.png',
    psychic: `../src/assets/images/types/psychic.png`,
    rock: '../src/assets/images/types/rock.png',
    steel: '../src/assets/images/types/steel.png',
    water: '../src/assets/images/types/water.png',
}