export const Types = {
    bug: `/assets/images/types/bug.png`,
    dark: `/assets/images/types/dark.png`,
    dragon: '/assets/images/types/dragon.png',
    electric: '/assets/images/types/electric.png',
    fairy: '/assets/images/types/fairy.png',
    fighting: '/assets/images/types/fighting.png',
    fire: '/assets/images/types/fire.png',
    flying: '/assets/images/types/flying.png',
    ghost: '/assets/images/types/ghost.png',
    grass: '/assets/images/types/grass.png',
    ground: '/assets/images/types/ground.png',
    ice: '/assets/images/types/ice.png',
    normal: '/assets/images/types/normal.png',
    poison: '/assets/images/types/poison.png',
    psychic: `/assets/images/types/psychic.png`,
    rock: '/assets/images/types/rock.png',
    steel: '/assets/images/types/steel.png',
    water: '/assets/images/types/water.png',
}